db:
  image: postgres:9.3
client_build:
  extends:
    file: docker-compose-base.yml
    service: client_build
server:
  extends:
    file: docker-compose-base.yml
    service: server
  links:
    - db
    - client_build
