db:
  image: postgres:9.3
frontend-watcher:
  extends:
    file: docker-compose-base.yml
    service: frontend-watcher
server:
  extends:
    file: docker-compose-base.yml
    service: server
  links:
    - db
    - frontend-watcher
